### ISSUE TITLE
 [nginx] Provide Open Source Disclosure Information for every released version of nginx in a timely manner!

### ISSUE THREAD

**Issue by AVL-OpenSourceOffice2** [bitnami/containers#68032]
We are using the nginx docker application that is provided by bitnami. 
To ensure FOSS compliance we are dependent on the Open Source Disclosure Information which is provided by Bitnami under the following link -> https://bitnami.com/open-source
Unfortunately the Open Source Disclosure Information for the application nginx (Open Source) for AMD64 is only available for the versions 1.24 and 1.25 and not for 1.26 and 1.27. We are not able to update to the latest version due to the missing Open Source Disclosure Information. 

If the information is available at some other place - please give me a hint! If not, when will the information become available?

Many thanks in advance!

**Comment by gongomgra** [comment]
Hi @AVL-OpenSourceOffice2,

Thanks for opening this issue. We have published the requested files for both AMD64 and ARM64 architectures at https://bitnami.com/open-source

**Comment by AVL-OpenSourceOffice2** [comment]
Thanks a lot for your quick reaction and response!

Best
Bernhard

**Comment by AVL-OpenSourceOffice2** [comment]
Dear nginx-team, 

we do want to offer the latest version of nginx (1.28 and 1.29) to our developers but have noticed, that once again the
Open Source Disclosure Information for the application nginx (Open Source) for AMD64 is still not available ... (3rd of September) 

Can you please check and tell me when you will be able to provide this information? 
Many thanks in advance

Bernhard

**Comment by carrodher** [comment]
As announced in https://github.com/bitnami/containers/issues/83267, no new versions are being published to the free Bitnami Docker Hub repository in favor of the secured-hardened catalog named Bitnami Secure Images available under subscription.

You can still build any image by yourself since the code is available in this GitHub repository under the Apache 2 license. Currently, only the source code of the latest branch is updated in the free offering; in the case of NGINX, that’s branch 1.29.

**Comment by AVL-OpenSourceOffice2** [comment]
Thanks for the clarification - we are already internally discussing to swap to your new secured images. 
However, we still require the Open Source Disclosure Information in order to fulfill the OS compliance for this image. 

Is it correct to assume that you will provide this information for the secured images as well? 
And if so, will you publish this information on https://bitnami.com/open-source or at some other place?

Thanks again for you help on this matter! 
Kind regards
Bernhard
